### ISSUE TITLE
调用popNotify.show()时报错

### ISSUE THREAD

**Issue by ZiuChen** [CKylinMC/PopNotify.js#1]
在你的脚本中它效果很好，我很想在自己的脚本中用，但很遗憾报错了，解决了很久都没有弄好

![image](https://user-images.githubusercontent.com/64892985/145031327-b4fc70f0-6ff1-432f-90bd-29880d85de8f.png)

我通过webpack将css与js文件打包，相当于将js代码直接注入到页面中，但是在调用：
```javascript
    popNotify.show("Hello", "world", "info");
```
出现报错

**Comment by ZiuChen** [comment]
我将源代码中的`window.popNotify.getNextYPos();`改为`popNotify.getNextYPos();`就可以了
:D

**Comment by CKylinMC** [comment]
很抱歉...
这个是我以前学习js时候做的一个小练习作品...所以里面其实有很多不成熟的或者很不好的地方...
同时感谢指正！

**Comment by ZiuChen** [comment]
不必抱歉
我也在学习当中，我很喜欢这个弹窗插件！
